'use client';

import { useState, useEffect } from 'react';
import { X, Loader2, Lightbulb } from 'lucide-react';
import type { WidgetConfig } from '@/types';

interface MetricExplanationModalProps {
  widget: WidgetConfig;
  onClose: () => void;
}

export function MetricExplanationModal({ widget, onClose }: MetricExplanationModalProps) {
  const [explanation, setExplanation] = useState<string>('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchExplanation() {
      try {
        setIsLoading(true);
        setError(null);

        const response = await fetch('/api/widgets/explain', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ widget }),
        });

        if (!response.ok) {
          const errorData = await response.json().catch(() => ({ error: 'Failed to fetch explanation' }));
          throw new Error(errorData.error || `Request failed (${response.status})`);
        }

        const data = await response.json();
        setExplanation(data.explanation);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'An unexpected error occurred');
      } finally {
        setIsLoading(false);
      }
    }

    fetchExplanation();
  }, [widget]);

  // Handle escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative w-full max-w-2xl mx-4 max-h-[80vh] bg-[var(--bg-primary)] rounded-2xl shadow-2xl border border-[var(--border-color)] overflow-hidden">
        {/* Header */}
        <div className="flex items-center gap-3 p-6 border-b border-[var(--border-color)]">
          <div className="p-2 rounded-lg bg-accent-purple/10">
            <Lightbulb size={20} className="text-accent-purple" />
          </div>
          <div className="flex-1">
            <h2 className="text-lg font-semibold text-[var(--text-primary)]">
              Metric Explanation
            </h2>
            <p className="text-sm text-[var(--text-secondary)]">
              {widget.title} • {widget.type.replace('_', ' ')}
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-[var(--bg-hover)] transition-colors"
          >
            <X size={20} className="text-[var(--text-secondary)]" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-96">
          {isLoading && (
            <div className="flex items-center justify-center py-12">
              <Loader2 size={24} className="animate-spin text-accent-purple" />
              <span className="ml-3 text-[var(--text-secondary)]">Analyzing metric...</span>
            </div>
          )}

          {error && (
            <div className="bg-accent-red/10 border border-accent-red/20 rounded-lg p-4 text-center">
              <p className="text-accent-red font-medium">Failed to generate explanation</p>
              <p className="text-sm text-[var(--text-secondary)] mt-1">{error}</p>
            </div>
          )}

          {explanation && (
            <div className="prose prose-sm max-w-none text-[var(--text-primary)]">
              <div className="whitespace-pre-wrap leading-relaxed">
                {explanation}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-[var(--border-color)] bg-[var(--bg-secondary)] rounded-b-2xl">
          <p className="text-xs text-[var(--text-muted)] text-center">
            This explanation is generated by AI and may need verification for critical business decisions.
          </p>
        </div>
      </div>
    </div>
  );
}