import type {
  VisualQueryConfig,
  ColumnMetadata,
  VisualFilter,
  AggregationOperation,
  OrderByOperation,
  JoinConfig,
  FormulaField
} from '@/types/visual-query';

interface SQLGenerationOptions {
  dialect?: 'postgres' | 'mysql' | 'sqlite';
  includeComments?: boolean;
  prettyFormat?: boolean;
}

/**
 * Converts a visual query configuration into SQL
 */
export function visualToSQL(
  config: VisualQueryConfig,
  options: SQLGenerationOptions = {}
): string {
  const {
    dialect = 'postgres',
    includeComments = false,
    prettyFormat = true
  } = options;

  const parts: string[] = [];

  if (includeComments) {
    parts.push('-- Generated by Visual Query Builder');
  }

  // Build SELECT clause
  parts.push(buildSelectClause(config, prettyFormat));

  // Build FROM clause
  parts.push(buildFromClause(config, prettyFormat));

  // Build JOIN clauses
  if (config.joins.length > 0) {
    parts.push(buildJoinClauses(config.joins, prettyFormat));
  }

  // Build WHERE clause
  if (config.filters.length > 0) {
    parts.push(buildWhereClause(config.filters, dialect, prettyFormat));
  }

  // Build GROUP BY clause
  if (config.groupBy.length > 0) {
    parts.push(buildGroupByClause(config.groupBy, prettyFormat));
  }

  // Build ORDER BY clause
  if (config.orderBy.length > 0) {
    parts.push(buildOrderByClause(config.orderBy, prettyFormat));
  }

  // Build LIMIT clause
  if (config.limit) {
    parts.push(buildLimitClause(config.limit, dialect, prettyFormat));
  }

  return parts.join(prettyFormat ? '\n' : ' ') + ';';
}

function buildSelectClause(config: VisualQueryConfig, prettyFormat: boolean): string {
  const selectItems: string[] = [];

  // Add regular columns
  config.columns
    .filter(col => col.isVisible)
    .forEach(col => {
      const columnRef = `${col.column.table}.${col.column.name}`;
      const alias = col.alias ? ` AS ${escapeIdentifier(col.alias)}` : '';
      selectItems.push(columnRef + alias);
    });

  // Add aggregations
  config.aggregations.forEach(agg => {
    const columnRef = `${agg.column.table}.${agg.column.name}`;
    const alias = agg.alias || `${agg.function}_${agg.column.name}`;
    selectItems.push(`${agg.function.toUpperCase()}(${columnRef}) AS ${escapeIdentifier(alias)}`);
  });

  // Add formulas (validated against safe function/operator allowlist)
  config.formulas.forEach(formula => {
    const alias = formula.alias || formula.name;
    const safeExpression = validateFormulaExpression(formula.expression);
    selectItems.push(`${safeExpression} AS ${escapeIdentifier(alias)}`);
  });

  // Fallback to * if no columns selected
  if (selectItems.length === 0) {
    selectItems.push('*');
  }

  const selectList = selectItems.join(prettyFormat ? ',\n       ' : ', ');
  return `SELECT ${prettyFormat ? '\n       ' : ''}${selectList}`;
}

function buildFromClause(config: VisualQueryConfig, prettyFormat: boolean): string {
  if (config.tables.length === 0) {
    throw new Error('At least one table must be specified');
  }

  const primaryTable = config.tables[0];
  const tableName = escapeIdentifier(primaryTable.name);
  const alias = primaryTable.alias ? ` ${escapeIdentifier(primaryTable.alias)}` : '';

  return `${prettyFormat ? '  ' : ''}FROM ${tableName}${alias}`;
}

function buildJoinClauses(joins: JoinConfig[], prettyFormat: boolean): string {
  const joinClauses = joins.map(join => {
    const joinType = join.joinType.toUpperCase();
    const rightTable = escapeIdentifier(join.rightTable);
    const condition = `${join.leftTable}.${join.leftColumn} = ${join.rightTable}.${join.rightColumn}`;

    const prefix = prettyFormat ? '  ' : '';
    return `${prefix}${joinType} JOIN ${rightTable} ON ${condition}`;
  });

  return joinClauses.join(prettyFormat ? '\n' : ' ');
}

function buildWhereClause(filters: VisualFilter[], dialect: string, prettyFormat: boolean): string {
  if (filters.length === 0) return '';

  const conditions = filters.map((filter, index) => {
    const condition = buildFilterCondition(filter, dialect);
    const logicalOp = index > 0 && filter.logicalOperator ? ` ${filter.logicalOperator} ` : '';
    return logicalOp + condition;
  });

  const whereConditions = conditions.join(prettyFormat ? '\n   ' : ' ');
  return `${prettyFormat ? ' ' : ''}WHERE ${whereConditions}`;
}

function buildFilterCondition(filter: VisualFilter, dialect: string): string {
  const columnRef = `${filter.column.table}.${filter.column.name}`;

  switch (filter.operation) {
    case 'equals':
      return `${columnRef} = ${formatValue(filter.value, filter.column.type)}`;
    case 'not_equals':
      return `${columnRef} != ${formatValue(filter.value, filter.column.type)}`;
    case 'greater_than':
      return `${columnRef} > ${formatValue(filter.value, filter.column.type)}`;
    case 'greater_than_or_equal':
      return `${columnRef} >= ${formatValue(filter.value, filter.column.type)}`;
    case 'less_than':
      return `${columnRef} < ${formatValue(filter.value, filter.column.type)}`;
    case 'less_than_or_equal':
      return `${columnRef} <= ${formatValue(filter.value, filter.column.type)}`;
    case 'contains':
      return `${columnRef} LIKE ${formatValue(`%${filter.value}%`, 'text')}`;
    case 'not_contains':
      return `${columnRef} NOT LIKE ${formatValue(`%${filter.value}%`, 'text')}`;
    case 'starts_with':
      return `${columnRef} LIKE ${formatValue(`${filter.value}%`, 'text')}`;
    case 'ends_with':
      return `${columnRef} LIKE ${formatValue(`%${filter.value}`, 'text')}`;
    case 'is_null':
      return `${columnRef} IS NULL`;
    case 'is_not_null':
      return `${columnRef} IS NOT NULL`;
    case 'in':
      if (Array.isArray(filter.value)) {
        const values = filter.value.map(v => formatValue(v, filter.column.type)).join(', ');
        return `${columnRef} IN (${values})`;
      }
      return `${columnRef} IN (${formatValue(filter.value, filter.column.type)})`;
    case 'not_in':
      if (Array.isArray(filter.value)) {
        const values = filter.value.map(v => formatValue(v, filter.column.type)).join(', ');
        return `${columnRef} NOT IN (${values})`;
      }
      return `${columnRef} NOT IN (${formatValue(filter.value, filter.column.type)})`;
    case 'between':
    case 'date_range':
      if (typeof filter.value === 'object' && 'start' in filter.value && 'end' in filter.value) {
        const start = formatValue(filter.value.start, filter.column.type);
        const end = formatValue(filter.value.end, filter.column.type);
        return `${columnRef} BETWEEN ${start} AND ${end}`;
      }
      throw new Error(`Invalid range value for ${filter.operation} operation`);
    default:
      throw new Error(`Unsupported filter operation: ${filter.operation}`);
  }
}

function buildGroupByClause(groupBy: string[], prettyFormat: boolean): string {
  const groupByFields = groupBy.map(escapeIdentifier).join(', ');
  return `${prettyFormat ? ' ' : ''}GROUP BY ${groupByFields}`;
}

function buildOrderByClause(orderBy: OrderByOperation[], prettyFormat: boolean): string {
  const orderByFields = orderBy.map(order => {
    const columnRef = `${order.column.table}.${order.column.name}`;
    return `${columnRef} ${order.direction.toUpperCase()}`;
  }).join(', ');

  return `${prettyFormat ? ' ' : ''}ORDER BY ${orderByFields}`;
}

function buildLimitClause(limit: number, dialect: string, prettyFormat: boolean): string {
  return `${prettyFormat ? ' ' : ''}LIMIT ${limit}`;
}

function formatValue(value: unknown, type: string): string {
  if (value === null || value === undefined) {
    return 'NULL';
  }

  switch (type) {
    case 'text':
      return `'${String(value).replace(/'/g, "''")}'`;
    case 'number':
      return String(Number(value));
    case 'boolean':
      return value ? 'TRUE' : 'FALSE';
    case 'date':
      if (value instanceof Date) {
        return `'${value.toISOString().split('T')[0]}'`;
      }
      return `'${String(value)}'`;
    default:
      return `'${String(value).replace(/'/g, "''")}'`;
  }
}

// Safe SQL functions allowed in formula expressions
const SAFE_SQL_FUNCTIONS = new Set([
  'SUM', 'COUNT', 'AVG', 'MIN', 'MAX', 'COALESCE', 'NULLIF',
  'ABS', 'CEIL', 'CEILING', 'FLOOR', 'ROUND', 'TRUNC', 'TRUNCATE',
  'UPPER', 'LOWER', 'TRIM', 'LTRIM', 'RTRIM', 'LENGTH', 'LEN',
  'CONCAT', 'SUBSTRING', 'SUBSTR', 'REPLACE', 'LEFT', 'RIGHT',
  'CAST', 'CONVERT', 'TO_DATE', 'TO_CHAR', 'TO_NUMBER',
  'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'IF', 'IFF',
  'DATEADD', 'DATEDIFF', 'DATE_TRUNC', 'EXTRACT', 'YEAR', 'MONTH', 'DAY',
  'CURRENT_DATE', 'CURRENT_TIMESTAMP', 'NOW',
  'COUNTIF', 'SUMIF', 'AVGIF',
  'DISTINCT', 'AS', 'AND', 'OR', 'NOT', 'IN', 'BETWEEN', 'IS', 'NULL', 'LIKE',
  'POWER', 'SQRT', 'LOG', 'LN', 'EXP', 'MOD',
  'ZEROIFNULL', 'NVL', 'IFNULL',
]);

// Dangerous patterns that should never appear in formulas
const DANGEROUS_PATTERNS = [
  /;\s*/,                     // Statement separator
  /--/,                       // SQL line comment
  /\/\*/,                     // SQL block comment
  /\bDROP\b/i,
  /\bDELETE\b/i,
  /\bINSERT\b/i,
  /\bUPDATE\b/i,
  /\bALTER\b/i,
  /\bCREATE\b/i,
  /\bEXEC\b/i,
  /\bEXECUTE\b/i,
  /\bGRANT\b/i,
  /\bREVOKE\b/i,
  /\bUNION\b/i,
  /\bINTO\b/i,
];

/**
 * Validate a formula expression against a safe subset of SQL functions and operators.
 * Rejects expressions containing dangerous SQL keywords or patterns.
 */
function validateFormulaExpression(expression: string): string {
  if (!expression || expression.length > 1000) {
    throw new Error('Formula expression is empty or too long (max 1000 chars)');
  }

  // Check for dangerous patterns
  for (const pattern of DANGEROUS_PATTERNS) {
    if (pattern.test(expression)) {
      throw new Error(`Formula contains disallowed SQL pattern: ${pattern}`);
    }
  }

  // Extract function names and validate against allowlist
  const functionCalls = expression.match(/\b([A-Z_][A-Z_0-9]*)\s*\(/gi) || [];
  for (const call of functionCalls) {
    const funcName = call.replace(/\s*\($/, '').toUpperCase();
    if (!SAFE_SQL_FUNCTIONS.has(funcName)) {
      throw new Error(`Formula uses disallowed function: ${funcName}`);
    }
  }

  return expression;
}

function escapeIdentifier(identifier: string): string {
  // Simple escaping - in production you might want more sophisticated escaping
  if (/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(identifier)) {
    return identifier;
  }
  return `"${identifier.replace(/"/g, '""')}"`;
}

/**
 * Validates a visual query configuration for SQL generation
 */
export function validateVisualQuery(config: VisualQueryConfig): string[] {
  const errors: string[] = [];

  // Check if at least one table is specified
  if (config.tables.length === 0) {
    errors.push('At least one table must be specified');
  }

  // Check if columns or aggregations are selected
  const hasVisibleColumns = config.columns.some(col => col.isVisible);
  const hasAggregations = config.aggregations.length > 0;
  const hasFormulas = config.formulas.length > 0;

  if (!hasVisibleColumns && !hasAggregations && !hasFormulas) {
    errors.push('At least one column, aggregation, or formula must be selected');
  }

  // Validate joins
  config.joins.forEach((join, index) => {
    if (!join.leftColumn || !join.rightColumn) {
      errors.push(`Join ${index + 1}: Both left and right columns must be specified`);
    }

    const leftTableExists = config.tables.some(t => t.name === join.leftTable);
    const rightTableExists = config.tables.some(t => t.name === join.rightTable);

    if (!leftTableExists) {
      errors.push(`Join ${index + 1}: Left table "${join.leftTable}" not found in query`);
    }
    if (!rightTableExists) {
      errors.push(`Join ${index + 1}: Right table "${join.rightTable}" not found in query`);
    }
  });

  // Validate filters
  config.filters.forEach((filter, index) => {
    if (!filter.column) {
      errors.push(`Filter ${index + 1}: Column must be specified`);
    }

    const operation = filter.operation;
    const requiresValue = !['is_null', 'is_not_null'].includes(operation);

    if (requiresValue && (filter.value === null || filter.value === undefined || filter.value === '')) {
      errors.push(`Filter ${index + 1}: Value is required for ${operation} operation`);
    }

    // Validate range operations
    if (['between', 'date_range'].includes(operation)) {
      if (typeof filter.value !== 'object' || !('start' in filter.value!) || !('end' in filter.value!)) {
        errors.push(`Filter ${index + 1}: Range operations require start and end values`);
      }
    }
  });

  // Validate formulas
  config.formulas.forEach((formula, index) => {
    if (!formula.expression.trim()) {
      errors.push(`Formula ${index + 1}: Expression cannot be empty`);
    }
    if (!formula.name.trim()) {
      errors.push(`Formula ${index + 1}: Name cannot be empty`);
    }
  });

  return errors;
}

/**
 * Estimates the complexity of a visual query
 */
export function estimateQueryComplexity(config: VisualQueryConfig): {
  score: number;
  factors: string[];
} {
  const factors: string[] = [];
  let score = 1;

  // Base complexity from table count
  if (config.tables.length > 1) {
    score += config.tables.length - 1;
    factors.push(`${config.tables.length} tables`);
  }

  // Join complexity
  if (config.joins.length > 0) {
    score += config.joins.length * 2;
    factors.push(`${config.joins.length} joins`);
  }

  // Filter complexity
  if (config.filters.length > 0) {
    score += config.filters.length;
    factors.push(`${config.filters.length} filters`);
  }

  // Aggregation complexity
  if (config.aggregations.length > 0) {
    score += config.aggregations.length;
    factors.push(`${config.aggregations.length} aggregations`);
  }

  // Grouping complexity
  if (config.groupBy.length > 0) {
    score += config.groupBy.length;
    factors.push(`grouped by ${config.groupBy.length} columns`);
  }

  // Formula complexity
  if (config.formulas.length > 0) {
    score += config.formulas.length * 2;
    factors.push(`${config.formulas.length} formulas`);
  }

  return { score, factors };
}